<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <sendSMS xmlns="http://Services.laotel.com/">
      <msg>
        <header>
          <userid>string</userid>
          <key>string</key>
          <trans_id>string</trans_id>
          <verson>string</verson>
        </header>
        <msisdn>string</msisdn>
        <headerSMS>string</headerSMS>
        <message>string</message>
        <sms_type>string</sms_type>
      </msg>
    </sendSMS>
  </soap:Body>
</soap:Envelope>